### ISSUE TITLE
myPosition commented out does not remove distance

### ISSUE THREAD

**Issue by sdetweil** [eouia/MMM-COVID-19#4]
the distance info can never be null,  as there is a default defined...

removed default and distance no longer displayed..

**Comment by eouia** [comment]
I'll inspect.

**Comment by eouia** [comment]
`myPosition: null,`(or false) is my intention to disable that feature. not commented out.

**Comment by eouia** [comment]
Anyway, I've changed that to `null` by default. So you can opt-in.

**Comment by sdetweil** [comment]
cool, thanks... config 'null' description was confusing  as it was a structure..
